### CURRENT STATUS
GET http://localhost:3001/current-user

### LOGOUT 
GET http://localhost:3001/logout

### REGISTER 
POST http://localhost:3001/signup
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "example_email_for_test@gmail.com"
}

### LOGIN
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### EDIT EMAIL
PUT http://localhost:3001/edit/email/for/qj8cRlg5BN_t
Content-Type: application/json

{
  "newValue": "new_email@gmail.com"
}

### EDIT USERNAME
PUT http://localhost:3001/edit/username/for/qj8cRlg5BN_t
Content-Type: application/json

{
  "newValue": "sfeesssffnge"
}