### GET ALL USERS 
GET http://localhost:3001/users

### LOGIN
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "testing",
  "password": "testing"
}

### CURRENT STATUS
GET http://localhost:3001/current-user

### LOGOUT 
GET http://localhost:3001/logout

### REGISTER 
POST http://localhost:3001/signup
Content-Type: application/json

{
  "username": "example_user",
  "password": "testing",
  "firstName": "Charlie",
  "lastName": "Bravo",
  "email": "example_email@gmail.com"
}

### EDIT PROFILE 
PUT http://localhost:3001/edit-profile
Content-Type: application/json

{
  "email": "newemail@gmail.com"
}